# Generated by Django 6.0.3 on 2026-03-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('problema_reportado', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('solucion_aplicada', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ingresado', 'Ingresado'), ('diagnostico', 'En Diagnóstico'), ('en_reparacion', 'En Reparación'), ('esperando_repuesto', 'Esperando Repuesto'), ('listo', 'Listo para Retirar'), ('entregado', 'Entregado'), ('sin_reparacion', 'Sin Reparación Posible')], default='ingresado', max_length=20)),
                ('importe_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importe_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('meses_garantia', models.PositiveIntegerField(default=3)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='equipos.equipo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='tecnicos.tecnico')),
            ],
        ),
    ]
