# Generated by Django 6.0.3 on 2026-03-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('netbook', 'Netbook'), ('cpu', 'CPU / PC de Escritorio'), ('monitor', 'Monitor'), ('impresora', 'Impresora'), ('laptop', 'Laptop'), ('otro', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('procesador', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('almacenamiento', models.CharField(blank=True, max_length=50)),
                ('descripcion_adicional', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='clientes.cliente')),
            ],
        ),
    ]
