# Generated by Django 6.0.3 on 2026-03-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='descuento',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='nota_solicitud',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='solicitud_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
